### PR TITLE
Add spring boot test

### PR DESCRIPTION
**Pull request by mythmon**
I did my best to muddle through Spring Boot's docs to make this. There are at least two deviations from [the spec](https://docs.google.com/document/d/1aLdE-JQ_2ahWYxqDdyRExtIgENPyViVXWupqX7id-do/edit#). The first is that the app doesn't sleep each request, since I couldn't figure out how to asynchronously sleep, and synchronously sleeping was incredibly unfair.

The second is that I haven't figured out a way to directly limit the number of workers/cores/threads/whatever like I did with the other apps. I think it's effectively using all of the cores that Molotov doesn't.

However, that doesn't seem to matter: Even with the advantages of not sleeping and using all the CPU it could want, spring-boot-test is slightly slower than sanic-test, and much slower than actix. I suspect there is something I've done wrong to cause that.

To test: In the `spring-boot-test` directory, run `./mvnw spring-boot:run`. You might need to install Maven, Java, or some other things to get that to work.

### CODE REVIEW

**Comment by mythmon** [comment]
@ncloudioj @jrconlin could you two take a look at this, and see if the implementation makes any terrible mistakes? I'm quite surprised that Sanic beat out Spring Boot, so I'd like some extra eyes.

**Comment by mythmon** [comment]
PS, here are some data I got with local testing (sorted by 95 percentile column):

```
                                   |   Request |        Average |   Median (ms) |   95 percentile (ms) |         Standard
 Server                            |     Count |   Latency (ms) |               |                      |   Deviation (ms)
-----------------------------------+-----------+----------------+---------------+----------------------+------------------
 actix-nosleep-3                   |   3117977 |          72.47 |         48.40 |               226.50 |           144.93
 actix-nosleep-1                   |   3234651 |          78.88 |         60.11 |               231.98 |           108.33
 actix-sleep-3                     |   3194281 |          88.23 |         59.87 |               236.01 |           157.72
 actix-nosleep-2                   |   3121594 |          85.05 |         63.19 |               241.25 |           135.65
 actix-sleep-1                     |   3068100 |          84.35 |         58.46 |               241.58 |           159.28
 actix-sleep-2                     |   3277572 |          86.72 |         58.67 |               246.00 |           160.57
 sanic-1                           |   2305203 |         170.57 |        161.19 |               249.68 |           101.20
 sanic-2                           |   2209042 |         168.43 |        155.60 |               266.35 |            81.00
 sanic-3                           |   2190321 |         171.28 |        159.44 |               266.96 |           104.12
 spring-boot-docker-4cpu-nosleep-2 |   2143460 |         182.66 |        161.01 |               288.89 |           139.85
 spring-boot-docker-4cpu-nosleep-3 |   2377845 |         176.98 |        161.16 |               291.12 |           120.12
 spring-boot-nosleep-2             |   1680454 |         257.47 |        241.35 |               379.97 |           108.45
 spring-boot-nosleep-3             |   1605218 |         268.31 |        248.61 |               398.01 |           114.62
 spring-boot-nosleep-1             |   1634808 |         235.06 |        241.78 |               403.14 |           149.30
 spring-boot-docker-4cpu-nosleep-1 |    267123 |        1563.74 |       1090.99 |              5273.89 |          1747.06
 spring-boot-syncsleep-3           |     47582 |       13273.88 |      14448.84 |             19046.98 |          4854.93
 spring-boot-syncsleep-2           |     56796 |       11521.25 |      11320.76 |             20057.22 |          5915.91
 spring-boot-syncsleep-1           |     56702 |       12258.59 |      11375.95 |             20372.49 |          6377.64
```

**Comment by jrconlin** [comment]
IIRC, one of the reasons that you can't restrict to cores inside of Java is because that's something controlled by the JVM (kind of like how you set memory available via a JVM option flag). 

I'm also wondering if the Java version might need to "warm up" a bit. The JVM does all sorts of "clever" things to optimize large apps, including some JIT like bits (thus the prevalence of `FactoryFactories` and what-not). It might be that the frameworks are doing some of that as well and you're seeing load costs being reflected into the latency. I have absolutely no idea if this is what's happening, just wondering based on some prior experiences with huge, monolithic apps and obsessive performance wonking.)

**Review by jrconlin — APPROVED** [review]

**Comment by mythmon** [comment]
I ran a warm up of about 1/4 traffic for 5 minutes, waited a bit, and then ran the same intensive test as above. The results were not significantly different than without the warm up.

**Pull request merged**
